11 cree une application docker pour facilité le developpement
UnionRolistes/Bot_Base pull request #13
Opened 2022-12-06 00:35 UTC by Fr-Dae

#10 #6 #11

2022-12-06 12:07 UTC, mortifia commented on Discord-Bot-main/Bot/.env
> +TOKEN=MTA0MDI3NTE3NTY4NzYwNjM3Mg.GC9Ggq.WrTUoMNXux9BLcH1DaWT1DD3uLAYBrme8Nw6Ec
preciser que ce fichier c'est pour le dev et pas pour la prod

2022-12-06 12:42 UTC, mortifia requested changes

2022-12-06 12:42 UTC, mortifia commented on Discord-Bot-main/Bot/UR-Bot.py
> +
donc en gros si c'est pas l'auteur on cree un log d'erreur ?

2022-12-06 12:42 UTC, mortifia commented on Discord-Bot-main/Bot/DebugBot.py
> +
c'est tout bète mais percise a quoi ca sert cette etape (pour les futur dev qui vont etre dessus

2022-12-06 12:42 UTC, mortifia commented on Discord-Bot-main/Bot/UR-Bot.py
> +bot.remove_command('help')
tu a retirer `$help` ?

2022-12-06 12:42 UTC, mortifia commented on Discord-Bot-main/Bot/UR-Bot.py
> +@bot.command(name="ping")
pour chaque commandes 
voir pour expliquer ce que ca fait 

soit ici ou soit au event.py

2022-12-06 12:42 UTC, mortifia commented on Discord-Bot-main/Bot/event.py
> +    embed = discord.Embed(url="http://presentation.unionrolistes.fr/?webhook=https://discord.com/api/webhooks/875068900612665396/DJusy0eGs9Xyx2os-dodBVfWia2fbhfBzfmnDM9g-30ozoFYAuZBHVXaD9TKaC1wwBwg",
pourquoi l'url est en dur ?
faudrai pouvoir le changé non en variable d'environement ?

2022-12-06 12:42 UTC, mortifia commented on Discord-Bot-main/Bot/event.py
> +    embed.set_footer(text="Union Roliste dev presentation.", icon_url="https://avatars.githubusercontent.com/u/62179928?s=200&v=4")
c'est prevu qu'on puisse changer pour mettre autre choses donc pour le footer que ca puisse etre changé

oui oui ca arrivera pas avant longtemp xD

2022-12-06 12:42 UTC, mortifia commented on Discord-Bot-main/Bot/event.py
> +    embed.set_footer(text="Union Roliste commands helper.", icon_url="https://avatars.githubusercontent.com/u/62179928?s=200&v=4")
comme au dessus :P

2022-12-06 12:42 UTC, mortifia commented on Discord-Bot-main/Install/LaunchInstall.bat
> +powershell -exec bypass .\Install.ps1 -image_name ur-bot-image-ubuntu -container_name ur-bot-container -run
normalement il faut seulement utiliser les commande docker et docker-compose

2022-12-06 12:42 UTC, mortifia commented on Discord-Bot-main/README.md
> +# Discord-Bot
ca manque d'explication 

- instalation
- config
- usage
- list command

2022-12-08 00:40 UTC, Fr-Dae reviewed
ok

2022-12-08 00:41 UTC, Fr-Dae commented
@mortifia aled c'est encore cassé

2022-12-08 12:46 UTC, Sx-Cheats approved these changes
TEST

2022-12-08 12:53 UTC, Sx-Cheats approved these changes
TEST 2

2022-12-08 12:54 UTC, Sx-Cheats requested changes
TEST 3 ? ...

2022-12-08 13:43 UTC, Sx-Cheats approved these changes
ALED J'Y ARRIVE PAS.

2022-12-08 16:42 UTC, Sx-Cheats approved these changes
Approve ...

2022-12-08 16:47 UTC, Sx-Cheats requested changes
TEST 4 ...

2022-12-08 16:47 UTC, Sx-Cheats approved these changes

2022-12-08 16:49 UTC, Sx-Cheats approved these changes

2022-12-08 16:50 UTC, merged